- id: pretty-format-golang
  name: Go Formatter
  description: Runs gofmt over golang source files.
  entry: pretty-format-golang
  language: python
  types: [go]
  minimum_pre_commit_version: '1'
- id: pretty-format-ini
  name: Pretty format INI
  description: This hook sets a standard for formatting INI files.
  entry: pretty-format-ini
  language: python
  types: [ini]
  minimum_pre_commit_version: '1'
- id: pretty-format-java
  name: Google Java Formatter
  description: Runs Google Java Formatter over Java source files
  entry: pretty-format-java
  language: docker
  types: [java]
  # this is needed because the hook downloads google-java-formatter and
  # we don't have yet a nice way of ensuring a single download over multiple runs
  require_serial: true
  minimum_pre_commit_version: '1'
- id: pretty-format-kotlin
  name: KTLint
  description: Runs KTLint (or ktfmt) over Kotlin source files
  entry: pretty-format-kotlin
  language: python
  types: [kotlin]
  minimum_pre_commit_version: '1'
  # this is needed because the hook downloads ktlint and we don't have yet a
  # nice way of ensuring a single download over multiple runs
  require_serial: true
- id: pretty-format-rust
  name: cargo-fmt
  description: Runs cargo fmt over Rust source files
  entry: pretty-format-rust
  language: python
  types: [rust]
  minimum_pre_commit_version: '1'
- id: pretty-format-toml
  name: Pretty format TOML
  description: This hook sets a standard for formatting TOML files.
  entry: pretty-format-toml
  language: python
  types: [toml]
  minimum_pre_commit_version: '1'
- id: pretty-format-yaml
  name: Pretty format YAML
  description: This hook sets a standard for formatting YAML files.
  entry: pretty-format-yaml
  language: python
  types: [yaml]
  minimum_pre_commit_version: '1'
